apiVersion: v1
kind: Service
metadata:
  name: coredns-rdns 
  labels:
    app: coredns-rdns 
spec:
  ports:
  - port: 53
    protocol: TCP
    name: dns-tcp
  - port: 53 
    protocol: UDP 
    name: dns-udp
  type: NodePort
  selector:
    app: coredns-rdns 
          # run: coredns-rdns 
