#!/usr/bin/env bash
set -e
shopt -s expand_aliases
alias kubectl='microk8s kubectl'
# kubectl apply -f mysql-pv.yml
kubectl delete -f mysql-deployment.yml 

# psql -h localhost -U postgresadmin1 --password -p 31070 postgresdb
